### ISSUE TITLE
Compose Kibana docker image

### ISSUE THREAD

**Issue by jdelagnes** [jdelagnes/playground#7]
Using image kibana:7.0.0, compose it with elasticsearch and run the complete stack.

**Comment by jdelagnes** [comment]
# Kibana docker image

https://www.elastic.co/guide/en/kibana/current/docker.html

# Docker compose file `docker-compose.yml`

```
# version: '3'

services:
  elasticsearch:
    image: elasticsearch:7.0.0
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk-network
  kibana:
    image: kibana:7.0.0
    environment:
      - elasticsearch.hosts=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - elk-network
    depends_on:
      - elasticsearch

volumes:
  elasticsearch:
    driver: local
  kibana:
    driver: local

networks:
  elk-network:
```
# Check everything is running

Go to http://127.0.0.1:5601
