### ISSUE TITLE
Compose Elastisearch docker image

### ISSUE THREAD

**Issue by jdelagnes** [jdelagnes/playground#8]
Using image `elasticsearch:7.0.0`, compose it and run the stack.

**Comment by jdelagnes** [comment]
Elasticsearch image documentation is available at https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html

The `docker-compose.yml`file content is :

```yaml
version: '3'

services:
  elasticsearch:
    image: elasticsearch:7.0.0
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk-network
volumes:
  elasticsearch:
    driver: local

networks:
  elk-network:
```
